/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fasthardware_internal_NativeFastHardware */

#ifndef _Included_fasthardware_internal_NativeFastHardware
#define _Included_fasthardware_internal_NativeFastHardware
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jdouble JNICALL Java_fasthardware_internal_NativeFastHardware_nativeGetGlobalCpuUsage
  (JNIEnv *, jclass);

JNIEXPORT jdoubleArray JNICALL Java_fasthardware_internal_NativeFastHardware_nativeGetPerCoreCpuUsage
  (JNIEnv *, jclass);

JNIEXPORT jlong JNICALL Java_fasthardware_internal_NativeFastHardware_nativeGetTotalMemoryBytes
  (JNIEnv *, jclass);

JNIEXPORT jlong JNICALL Java_fasthardware_internal_NativeFastHardware_nativeGetFreeMemoryBytes
  (JNIEnv *, jclass);

JNIEXPORT jdouble JNICALL Java_fasthardware_internal_NativeFastHardware_nativeGetCpuTemperatureCelsius
  (JNIEnv *, jclass);

JNIEXPORT jdouble JNICALL Java_fasthardware_internal_NativeFastHardware_nativeGetGpuTemperatureCelsius
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
